# Generated by Django 5.1.4 on 2026-01-06 14:11

import departmentadmin.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companyadmin', '0001_initial'),
        ('systemadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeviceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, help_text='Date this report covers (usually yesterday)')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('custom', 'Custom Report')], db_index=True, default='daily', help_text='Type of report', max_length=20)),
                ('csv_file', models.FileField(help_text='Generated CSV file', upload_to=departmentadmin.models.report_upload_path)),
                ('total_sensors', models.IntegerField(default=0, help_text='Number of sensors included')),
                ('trend_sensors_count', models.IntegerField(default=0, help_text='Number of trend/time-series sensors')),
                ('latest_sensors_count', models.IntegerField(default=0, help_text='Number of latest value sensors')),
                ('data_points_analyzed', models.IntegerField(default=0, help_text='Total data points analyzed from InfluxDB')),
                ('generation_time_seconds', models.FloatField(blank=True, help_text='Time taken to generate report', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_errors', models.TextField(blank=True, help_text='Any errors during generation')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='companyadmin.department')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='companyadmin.device')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='companyadmin.departmentmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='systemadmin.tenant')),
            ],
            options={
                'verbose_name': 'Daily Device Report',
                'verbose_name_plural': 'Daily Device Reports',
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'department', 'report_date'], name='departmenta_tenant__bd294a_idx'), models.Index(fields=['device', 'report_date'], name='departmenta_device__ae4936_idx'), models.Index(fields=['report_type'], name='departmenta_report__ff4ea9_idx'), models.Index(fields=['created_at'], name='departmenta_created_f6fb7f_idx')],
                'unique_together': {('tenant', 'device', 'report_date', 'report_type')},
            },
        ),
        migrations.CreateModel(
            name='DeviceUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments_made', to='accounts.user')),
                ('department', models.ForeignKey(help_text='Department context for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='device_user_assignments', to='companyadmin.department')),
                ('device', models.ForeignKey(help_text='Device being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='companyadmin.device')),
                ('user', models.ForeignKey(help_text='User receiving access to device', on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Device User Assignment',
                'verbose_name_plural': 'Device User Assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['device', 'is_active'], name='departmenta_device__deeff4_idx'), models.Index(fields=['user', 'is_active'], name='departmenta_user_id_9f4e45_idx'), models.Index(fields=['department', 'is_active'], name='departmenta_departm_d026ce_idx')],
                'unique_together': {('device', 'user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('medium', 'Medium'), ('high', 'High'), ('resolved', 'Resolved')], db_index=True, default='initial', max_length=10)),
                ('breach_type', models.CharField(choices=[('upper', 'Upper Limit Breach'), ('lower', 'Lower Limit Breach')], db_index=True, max_length=10)),
                ('breach_value', models.FloatField(help_text='Sensor value that caused the breach')),
                ('limit_value', models.FloatField(help_text='The limit that was breached')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_to_medium_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_to_high_at', models.DateTimeField(blank=True, null=True)),
                ('sensor_metadata', models.ForeignKey(help_text='Link to sensor metadata with configured limits', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companyadmin.sensormetadata')),
            ],
            options={
                'verbose_name': 'Sensor Alert',
                'verbose_name_plural': 'Sensor Alerts',
                'db_table': 'departmentadmin_sensoralert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sensor_metadata', 'status'], name='departmenta_sensor__ab36e6_idx'), models.Index(fields=['status', 'created_at'], name='departmenta_status_6b8b5d_idx'), models.Index(fields=['breach_type', 'status'], name='departmenta_breach__718adf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['initial', 'medium', 'high'])), fields=('sensor_metadata',), name='unique_active_alert_per_sensor')],
            },
        ),
    ]
