# Generated by Django 5.1.4 on 2025-12-09 07:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(help_text="InfluxDB database name (e.g., 'production_iot')", max_length=100)),
                ('base_api', models.URLField(help_text="InfluxDB API base URL (e.g., 'http://influxdb.company.com:8086')", max_length=500, validators=[django.core.validators.URLValidator()])),
                ('api_username', models.CharField(help_text='InfluxDB username for Basic Auth', max_length=100)),
                ('api_password', models.CharField(help_text='InfluxDB password for Basic Auth', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this configuration is active')),
                ('is_connected', models.BooleanField(default=False, help_text='Last connection test result')),
                ('last_tested_at', models.DateTimeField(blank=True, help_text='When connection was last tested', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When data was last fetched from InfluxDB', null=True)),
                ('connection_error', models.TextField(blank=True, help_text='Last connection error message (if any)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this configuration')),
            ],
            options={
                'verbose_name': 'Asset Configuration',
                'verbose_name_plural': 'Asset Configurations',
                'db_table': 'asset_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=200, unique=True)),
                ('department_type', models.CharField(help_text='e.g., Manufacturing, Quality Control, Packaging', max_length=100)),
                ('plant_location', models.CharField(help_text='e.g., Building A, Floor 3, Zone 2', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Primary department email for notifications', max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this department is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='department_is_acti_8ce068_idx'), models.Index(fields=['name'], name='department_name_9f4150_idx'), models.Index(fields=['created_at'], name='department_created_919db1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text="Device ID from InfluxDB (e.g., '1', '2', 'PUMP_01')", max_length=100)),
                ('display_name', models.CharField(help_text="Human-readable name for the device (e.g., 'Chiller Unit 1')", max_length=200)),
                ('measurement_name', models.CharField(help_text='InfluxDB measurement name this device belongs to', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional device information (location, type, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments that can access this device', related_name='devices', to='companyadmin.department')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'companyadmin_device',
                'ordering': ['measurement_name', 'device_id'],
                'unique_together': {('measurement_name', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Field name in InfluxDB (e.g., 'temperature', 'pressure')", max_length=200)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable name (defaults to field_name if blank)', max_length=200)),
                ('field_type', models.CharField(choices=[('float', 'Float'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('string', 'String'), ('unknown', 'Unknown')], default='unknown', help_text='Data type of this sensor field', max_length=20)),
                ('category', models.CharField(choices=[('sensor', 'Sensor Data'), ('info', 'Information'), ('slave', 'Slave ID')], default='sensor', help_text='Is this a sensor or just info?', max_length=20)),
                ('unit', models.CharField(blank=True, help_text="Unit of measurement (e.g., '°C', 'PSI', '%')", max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional sensor information (sample_value, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='Device this sensor belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='companyadmin.device')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'companyadmin_sensor',
                'ordering': ['device', 'field_name'],
                'unique_together': {('device', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='SensorMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text="User-friendly display name (e.g., 'Compressor Temperature')", max_length=255)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., °C, kWh, bar, %, RPM)', max_length=50)),
                ('upper_limit', models.FloatField(blank=True, help_text='Upper threshold for alerts/visualization', null=True)),
                ('lower_limit', models.FloatField(blank=True, help_text='Lower threshold for alerts/visualization', null=True)),
                ('central_line', models.FloatField(blank=True, help_text='Target/setpoint value (central line on graph)', null=True)),
                ('show_time_series', models.BooleanField(default=True, help_text='Show time series line chart')),
                ('show_latest_value', models.BooleanField(default=False, help_text='Show latest value as big number card')),
                ('show_digital', models.BooleanField(default=False, help_text='Show as digital display (ON/OFF for boolean sensors)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.OneToOneField(help_text='Link to the sensor', on_delete=django.db.models.deletion.CASCADE, related_name='metadata_config', to='companyadmin.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Metadata',
                'verbose_name_plural': 'Sensor Metadata',
                'db_table': 'companyadmin_sensor_metadata',
                'ordering': ['sensor__field_name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_department', models.CharField(blank=True, help_text='Specific role in this department', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='companyadmin.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='accounts.user')),
            ],
            options={
                'db_table': 'department_membership',
                'indexes': [models.Index(fields=['user', 'is_active'], name='department__user_id_38e7d7_idx'), models.Index(fields=['department', 'is_active'], name='department__departm_7f60e5_idx')],
                'unique_together': {('user', 'department')},
            },
        ),
    ]
