# Generated by Django 5.1.4 on 2026-01-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(help_text="Friendly name (e.g., 'Factory 1 - Mumbai', 'Building A - Pune')", max_length=200, unique=True)),
                ('db_name', models.CharField(help_text='InfluxDB database name', max_length=100)),
                ('base_api', models.URLField(help_text='InfluxDB API URL (e.g., http://influxdb.example.com:8086)', max_length=500)),
                ('api_username', models.CharField(max_length=100)),
                ('api_password', models.CharField(max_length=100)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connection_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'InfluxDB Configuration',
                'verbose_name_plural': 'InfluxDB Configurations',
                'db_table': 'asset_config',
                'ordering': ['config_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('department_type', models.CharField(max_length=100)),
                ('plant_location', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'companyadmin_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, choices=[('industrial_sensor', 'Industrial Sensor'), ('asset_tracking', 'Asset Tracking')], max_length=50, null=True)),
                ('device_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('measurement_name', models.CharField(max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_config', models.ForeignKey(help_text='Which InfluxDB instance this device came from', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='companyadmin.assetconfig')),
                ('departments', models.ManyToManyField(blank=True, related_name='devices', to='companyadmin.department')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'companyadmin_device',
                'ordering': ['asset_config', 'measurement_name', 'device_id'],
                'unique_together': {('asset_config', 'measurement_name', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('sensor', 'Sensor Data'), ('info', 'Device Info'), ('slave', 'Slave ID')], default='sensor', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='companyadmin.device')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'companyadmin_sensor',
                'ordering': ['device', 'category', 'field_name'],
                'unique_together': {('device', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='AssetTrackingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(limit_choices_to={'device_type': 'asset_tracking'}, on_delete=django.db.models.deletion.CASCADE, related_name='asset_tracking_config', to='companyadmin.device')),
                ('info_card_sensors', models.ManyToManyField(blank=True, related_name='info_card_configs', to='companyadmin.sensor')),
                ('latitude_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lat_configs', to='companyadmin.sensor')),
                ('longitude_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lng_configs', to='companyadmin.sensor')),
                ('map_popup_sensors', models.ManyToManyField(blank=True, related_name='map_popup_configs', to='companyadmin.sensor')),
                ('time_series_sensors', models.ManyToManyField(blank=True, related_name='time_series_configs', to='companyadmin.sensor')),
            ],
            options={
                'verbose_name': 'Asset Tracking Configuration',
                'verbose_name_plural': 'Asset Tracking Configurations',
                'db_table': 'companyadmin_asset_tracking_config',
            },
        ),
        migrations.CreateModel(
            name='SensorMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('lower_limit', models.FloatField(blank=True, null=True)),
                ('center_line', models.FloatField(blank=True, null=True)),
                ('upper_limit', models.FloatField(blank=True, null=True)),
                ('data_types', models.JSONField(default=list)),
                ('data_nature', models.CharField(choices=[('spot', 'Spot Reading'), ('cumulative', 'Cumulative'), ('digital_io', 'Digital I/O')], default='spot', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_config', to='companyadmin.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Metadata',
                'verbose_name_plural': 'Sensor Metadata',
                'db_table': 'companyadmin_sensor_metadata',
            },
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='companyadmin.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Department Membership',
                'verbose_name_plural': 'Department Memberships',
                'db_table': 'companyadmin_department_membership',
                'unique_together': {('user', 'department')},
            },
        ),
    ]
