# Generated by Django 5.1.4 on 2025-12-09 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.CharField(help_text='Used for subdomain routing (e.g., acme.yourdomain.com)', max_length=63, unique=True)),
                ('schema_name', models.CharField(help_text='Database schema name (auto-generated from subdomain)', max_length=63, unique=True)),
                ('tenant_code', models.CharField(blank=True, help_text='Unique tenant access code (e.g., lime0026) - used for login portal', max_length=20, null=True, unique=True)),
                ('auto_drop_schema', models.BooleanField(default=False, help_text='Automatically drop schema when tenant is deleted')),
                ('auto_create_schema', models.BooleanField(default=True, help_text='Automatically create schema when tenant is created')),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this tenant')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Full domain (e.g., acme.yourdomain.com)', max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary domain for this tenant')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='systemadmin.tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domain',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
    ]
